@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User
User --> Front: clique sur bouton 'J'ai perdu un objet'
Front --> Front: affiche formulaire
User --> Front: clique sur le bouton 'Valider'
Front --> Back: fetch(/ajoutObjetPerdu)
Back --> Back: new ObjetPerdu(intitule, description, adresse, date, adresseMail)

@enduml