language: node_js
node_js:
  - "14.16.0"

git:
  depth: 1

cache:
  directories:
    - node_modules

before_install:
  - cd perdupn_back_end
  - npm update

install:
  - npm install

script:
  - npm test
  - npm run coveralls

# safelist and blocklist
branches:
  only:
    - main
  except:
    - dev
    - carte_localisations_objets

#Notifications

