@startuml
'https://plantuml.com/class-diagram

class Application
interface Objet
{
    +getLocalisation() : Localisation
}
class ObjetTrouve
{
    -Localisation l
    +ObjetTrouve(in : Localisation) : void
}
class ObjetPerdu
{
    -Localisation l
    +ObjetTrouve(in : Localisation) : void
}
interface Localisation
{
    +getLongtitde(): double
    +getLatitude(): double
}
class LocalisationPrecise
{
    -double longitude
    -double latitude
    +LocalisationPrecise(in: double, double): void
}
class LocalisationFloue
{
    -double longitude
    -double latitude
    +LocalisationFloue(in: double, double): void
}

class User
{
    -LocalisationPrecise l
    +User(in : LocalisationPrecise) : void
    +getLocalisation() : LocalisationPrecise
    +distanceObjetUser(in: Localisation) : double
}


ObjetTrouve "1...*" <-- "1" Application
ObjetPerdu "1...*" <-- "1" Application
Objet <|.. ObjetPerdu
Objet <|.. ObjetTrouve
Localisation <|.. LocalisationPrecise
Localisation <|.. LocalisationFloue
LocalisationPrecise "1" <.. ObjetTrouve
LocalisationFloue "1" <.. ObjetPerdu
LocalisationPrecise "1" <.. User
ObjetTrouve "1...*" <.. User
ObjetPerdu "1...*" <.. User
User "1...*" <-- "1" Application


@enduml