@startuml
'https://plantuml.com/class-diagram

class Application
enum Categorie
{
    HIGH-TECH
    CLES
    VETEMENTS
}
class Calculateur
{
    +getDistanceLocalisationFloue(in locUser : LocalisationPrecise, loc : LocalisationFloue) : void
    +getDistanceLocalisationPrecise(in locUser : LocalisationPrecise, loc : LocalisationPrecise) : void
}
interface Item
{
    +getLocalisation() : Localisation
    +getCategorie() : Categorie
}
class ObjetTrouve
{
    -Localisation l
    -Categorie c
    +ObjetTrouve(in l : Localisation, c : Categorie) : void
    +getCategorie() : Categorie
    +getLocalisation() : Localisation
    +getDistance(in l : LocalisationPrecise) : Calculateur
}
class ObjetPerdu
{
    -Localisation l
    -Categorie c
    +ObjetPerdu(in l : Localisation, c : Categorie) : void
    +getCategorie() : Categorie
    +getLocalisation() : Localisation
    +getDistance(in l : LocalisationPrecise) : Calculateur
}
class Position
{
    - double longitude
    - double latitude
    + Position(in longitude : double, latitude : double)
    + getLongitude() : double
    + getLatitude() : double
}
interface Localisation
{
    +Localisation(in p : Position): void
    +getPosition(): Position
}
class LocalisationPrecise
{
    +LocalisationPrecise(in p : Position): void
    +getPosition(): Position
}
class LocalisationFloue
{
    +Localisation(in p : Position, r : double): void
    +getPosition(): Position
    +getRayon(): double
}


ObjetTrouve "1...*" --* Application
ObjetPerdu "1...*" --* Application

Categorie <.. ObjetTrouve
Categorie <.. ObjetPerdu

Item <|.. ObjetPerdu
Item <|.. ObjetTrouve


Localisation <|.. LocalisationPrecise
Localisation <|.. LocalisationFloue

LocalisationPrecise "1" <.. ObjetTrouve
LocalisationFloue "1" <.. ObjetPerdu

Position "1" <-- Localisation

Calculateur "1" <-- ObjetTrouve
Calculateur "1" <-- ObjetPerdu

@enduml