@startuml
'https://plantuml.com/class-diagram

class Application
enum Categorie
{
    HIGH-TECH
    CLES
    VETEMENTS
}
interface Calculateur
{
    getDistance(in locUser : LocalisationPrecise, loc : Localisation) : void
}
class CalculateurFloue
{
    +getDistance(in locUser : LocalisationPrecise, loc : LocalisationFloue) : void
}
class CalculateurPrecis
{
    +getDistance(in locUser : LocalisationPrecise, loc : LocalisationPrecise) : void
}
interface Item
{
}
class ObjetTrouve
{
    -Localisation l
    -Categorie c
    +ObjetTrouve(in l : Localisation, c : Categorie, description : String, intitule : String, date : Date) : void
    +getDistance(in l : LocalisationPrecise) : Calculateur
}
class ObjetPerdu
{
    -Localisation l
    -Categorie c
    +ObjetPerdu(in l : Localisation, c : Categorie, description : String, intitule : String, date : Date) : void
    +getDistance(in l : LocalisationPrecise) : Calculateur
}
class Position
{
    - double longitude
    - double latitude
    + Position(in longitude : double, latitude : double)
}
interface Localisation
{
    +Localisation(in p : Position): void
}
class LocalisationPrecise
{
    +LocalisationPrecise(in p : Position): void
}
class LocalisationFloue
{
    +LocalisationFloue(in p : Position, r : double): void
}


ObjetTrouve "1...*" --* Application
ObjetPerdu "1...*" --* Application

Categorie <.. ObjetTrouve
Categorie <.. ObjetPerdu

Item <|.. ObjetPerdu
Item <|.. ObjetTrouve

Localisation <|.. LocalisationPrecise
Localisation <|.. LocalisationFloue

LocalisationPrecise "1" <.. ObjetTrouve
LocalisationFloue "1" <.. ObjetPerdu

Position "1" <-- Localisation

Calculateur "1" <-- ObjetTrouve
Calculateur "1" <-- ObjetPerdu

Calculateur <|.. CalculateurFloue
Calculateur <|.. CalculateurPrecis

@enduml